config/routes.rb
Rails.application.routes.draw do
  resources :musics
  root "musics#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
	validates :title, :artist, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  # これにより、４つのアクションにset_musicで定義したものを書く必要がなくなる。
  def top
  end

  def index
  	@music = Music.new
  	@musics = Music.all.order(created_at: :desc) #降順
  end

  def show
  end

  def create
  	@music = Music.new(music_params)
  	@musics = Music.all
  	if @music.save
  	   redirect_to music_path(@music), notice: "Music was successfully created."
  	else
  	   render "index"
  	end
  end

  def edit
  end

  def update
  	if @music.update(music_params)
  	   redirect_to music_path(@music), notice: "Music was successfully update."
  	else
  	   render "edit"
  	end
  end

  def destroy
  	@music.destroy
  	redirect_to musics_path, notice: "Music was successfully destroyed."
  end

  private

  def set_music
  	@music = Music.find(params[:id])
  end

  def music_params
  	params.require(:music).permit(:title, :artist)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musics/edit.html.erb
<h2>Editing Music</h2>

<%= form_for (@music) do |f| %>

	<% if @music.errors.any? %>
		<%= @music.errors.count %>error prohibited this music from being saved:<br>
		<ul>
			<% @music.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<p>Title<br>
	<%= f.text_field :title %></p>

	<p>Aritist<br>
	<%= f.text_field :artist %></p>

	<p><%= f.submit "Update Music" %></p>

	<p><%= link_to "Show", music_path(@music) %> |
	<%= link_to "Back", musics_path %></p>


<% end %>

app/views/musics/index.html.erb
<p><%= flash[:notice] %></p>

<h2>Musics</h2>
<table width="800">
	<tr>
		<th>Title</th>
		<th>Artist</th>
	</tr>
	<% @musics.each do |music| %>
		<tr align="center">
			<td><%= link_to music.title, music_path(music) %></td>
			<td><%= music.artist %></td>
			<td><%= link_to "Edit", edit_music_path(music) %></td>
			<td><%= link_to "Destroy", music_path(music), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
		</tr>
	<% end %>
</table>

<h2>New Music</h2>
<%= form_for (@music) do |f| %>

	<% if @music.errors.any? %>
		<%= @music.errors.count %>error prohibited this music from being saved:<br>
		<ul>
			<% @music.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<p>Title<br>
	<%= f.text_field :title %></p>

	<p>Aritist<br>
	<%= f.text_field :artist %></p>

	<p><%= f.submit "Create Music" %></p>


<% end %>

app/views/musics/show.html.erb
<p><%= flash[:notice] %></p>


	<%= @music.title %>
	<%= @music.artist %>

	<%= link_to "Edit", edit_music_path(@music) %>
	<%= link_to "Back", musics_path %>

app/views/musics/top.html.erb
<h1>Muuへようこそ！</h1>

<%= link_to 'start', musics_path %>